### ISSUE TITLE
联合 workspaces 使用时出现的问题

### ISSUE THREAD

**Issue by YangFong** [wibetter/akfun#14]
我在使用时，出现了这么一个异常：

<img width="1017" alt="image" src="https://github.com/wibetter/akfun/assets/70502828/bb2a2bba-b749-485a-8f65-cdf2b520b316">

后续发现，原因在于 vue-template-compiler，它的 [package.json](https://github.com/vuejs/vue/blob/main/packages/template-compiler/package.json#L32-L34) 中，是这样的：

<img width="314" alt="image" src="https://github.com/wibetter/akfun/assets/70502828/0e6773e1-913d-4b14-a145-3fe800c84fba">

因为 vue-template-compiler 只限于在 Vue2 中使用，而我的其他包中使用到了 Vue3，这导致依赖在上升到同一层的情况下，产生了这么个错误。

**Comment by wibetter** [comment]
@YangFong  vue3的项目请使用https://github.com/wibetter/akfun/tree/feat-vue3，对应的包是：@wibetter/akfun
