### ISSUE TITLE
如何支持在开发模式下允许跨域访问，以支持项目作为微前端的子项目

### ISSUE THREAD

**Issue by lishengliang74** [wibetter/akfun#15]
项目作为微前端的子项目，需要在devServer上配置允许跨域请求：
devServer: {
      headers: {
            'Access-Control-Allow-Credentials': true,
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Headers': 'X-Requested-With,Content-Type',
            'Access-Control-Allow-Methods': 'PUT,POST,GET,DELETE,OPTIONS',
        },
}

请问如何在akfun中进行配置

**Comment by wibetter** [comment]
@lishengliang74  https://github.com/wibetter/akfun/blob/master/README.md 中有"接口代理配置"的说明，这里的代理实际上就是使用http-proxy-middleware实现的。
